<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-51JTP5G" failures="1" tests="1" name="delete" time="46.17" errors="0" timestamp="2021-09-13T18:15:50 IST">
  <testcase classname="adminTests.DeleteUserTest" name="deleteUser" time="36.651">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at adminTests.DeleteUserTest.deleteUser(DeleteUserTest.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser -->
</testsuite> <!-- delete -->
